name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker compose version

      - name: Copy .env.example to .env
        run: cp ./1-Integration-tests/.env.example ./1-Integration-tests/.env

      - name: Install dependencies
        working-directory: ./1-Integration-tests
        run: npm install

      - name: Grant execution permission to script
        run: chmod +x ./1-Integration-tests/scripts/run-integration.sh

      - name: Start services with Docker Compose
        working-directory: ./1-Integration-tests
        run: docker compose up -d

      - name: Run Integration script
        working-directory: ./1-Integration-tests
        run: npm run test:integration
