name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Ensure Docker Compose is available
      run: docker compose version

    - name: Copy .env.example to .env
      run: cp ./1-Integration-tests/.env.example ./1-Integration-tests/.env

    - name: Install dependencies
      run: npm install

    - name: Grant execution permission to script
      run: chmod +x ./1-Integration-tests/scripts/run-integration.sh

    - name: Start services with Docker Compose
      run: docker-compose up -d

    - name: Run Integration script
      run: cd 1-Integration-tests && npm run test:integration
